### ISSUE TITLE
MoneyModule seems configured but Jackson not deserializing

### ISSUE THREAD

**Issue by jeffjensen** [zalando/jackson-datatype-money#246]
If objectMapper.getRegisteredModuleIds() contains org.zalando.jackson.datatype.money.MoneyModule, why would this error still occur?
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `javax.money.MonetaryAmount` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
```

It seems the Money Jackson HttpMessageConverter not configured?  Is there another setup step I missed, e.g. also need to configure the converter?

Running with Spring Boot v2.3.1.RELEASE, Spring v5.2.7.RELEASE.

Configured by this in a @Configuration class:
```java
    @Bean
    public Module moneyModule()
    {
        return new MoneyModule();
    }
```

**Comment by whiskeysierra** [comment]
> It seems the Money Jackson HttpMessageConverter not configured?

How did you configure your JacksonHttpMessageConverter?

**Comment by jeffjensen** [comment]
> > It seems the Money Jackson HttpMessageConverter not configured?
> 
> How did you configure your JacksonHttpMessageConverter?

Spring Boot does it; can see AbstractJackson2HttpMessageConverter in use in this stack trace. However, I may misunderstand another configuration need.

```java
Caused by: org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class javax.money.MonetaryAmount]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `javax.money.MonetaryAmount` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 1, column: 138]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:272)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:257)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:105)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:998)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:981)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:741)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:641)
	at org.springframework.boot.test.web.client.TestRestTemplate.exchange(TestRestTemplate.java:852)
	... 129 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `javax.money.MonetaryAmount` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 1, column: 138]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1611)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:371)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3487)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:269)
```

**Comment by whiskeysierra** [comment]
> can see AbstractJackson2HttpMessageConverter in use in this stack trace

But how is that configured? Where does it come from?

**Comment by jeffjensen** [comment]
Spring Boot has a JacksonAutoConfiguration class and others that auto-configure ObjectMapper.  For example, it auto-registers any Spring bean of type com.fasterxml.jackson.databind.Module; from [1]:

> Any beans of type com.fasterxml.jackson.databind.Module are automatically registered with the auto-configured Jackson2ObjectMapperBuilder and are applied to any ObjectMapper instances that it creates. This provides a global mechanism for contributing custom modules when you add new features to your application.

Therefore, making MoneyModule a Spring bean like this:
```
    @Bean
    public Module moneyModule()
    {
        return new MoneyModule();
    }
```
has Boot automatically add it to ObjectMapper's modules.

MoneyModule automatically registers the Deserializers and Serializers so I think there is nothing more to configure; however, I'm wondering if I am missing something since a Money deserializer doesnt' run.

Do you have a valid Spring Boot configuration for MoneyModule to share?


[1] https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-customize-the-jackson-objectmapper

**Comment by whiskeysierra** [comment]
> JacksonAutoConfiguration

That one only configures the ObjectMapper and its modules. But my suspicion is that your JacksonHttpMessageConverter is not making use of that particular object mapper instance but another one (without the MoneyModule).

**Comment by andrewhj** [comment]
I have thrown together an example here: https://github.com/andrewhj/jackson-money-demo .  The serialization works using the spring boot auto configuration.  However, debugging shows that something in the RestTemplate uses a separate JacksonHttpMessageConverter.  Perhaps then this is a spring issue as to how why RestTemplate would use a different converter than the Controllers?

**Comment by whiskeysierra** [comment]
Spring auto wires a separate converter for the RestTemplate, but it should be using the very same ObjectMapper instance. See:

- RestTemplateAutoConfiguration
- HttpMessageConvertersAutoConfiguration
- JacksonHttpMessageConvertersConfiguration

If you put some break points in there you should be able to debug whether those are used and whether it's the same ObjectMapper instance.

**Comment by bradmac-ats** [comment]
In my case I was using `TestRestTemplate` in a `@SpringBootTest`, and I just needed to autowire the preconfigured `TestRestTemplate` instead of creating one myself.
