### ISSUE TITLE
Unable to parse CSV data

### ISSUE THREAD

**Issue by Gaibhne** [zalando/jackson-datatype-money#359]
There seems to be no path to using this module together with `jackson-dataformat-csv`.

## Description
When defining a column as `MonetaryAmount` and attempting to deserialize, the following error appears:

```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Missing property: 'amount'
 at [Source: (StringReader); line: 1, column: 608] (through reference chain: com.company.bank.convert.model.CsvMt940TransAction["Betrag"])
        at com.company.bank.convert.CsvImporter.deserialize(CsvImporter.java:121)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at one.util.streamex.PairSpliterator$PSOfRef.lambda$forEachRemaining$5(PairSpliterator.java:247)
        at java.base/java.nio.file.FileChannelLinesSpliterator.forEachRemaining(FileChannelLinesSpliterator.java:117)
        at one.util.streamex.PairSpliterator$PSOfRef.forEachRemaining(PairSpliterator.java:242)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:360)
        at com.company.bank.convert.CsvImporter.tryParse(CsvImporter.java:90)
        at com.company.bank.convert.App.main(App.java:45)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Missing property: 'amount'
 at [Source: (StringReader); line: 1, column: 608] (through reference chain: com.company.bank.convert.model.CsvMt940TransAction["Betrag"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:315)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:283)
        at com.fasterxml.jackson.databind.MappingIterator.readAll(MappingIterator.java:323)
        at com.fasterxml.jackson.databind.MappingIterator.readAll(MappingIterator.java:309)
        at com.company.bank.convert.CsvImporter.deserialize(CsvImporter.java:116)
        ... 13 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Missing property: 'amount'
 at [Source: (StringReader); line: 1, column: 608]
        at org.zalando.jackson.datatype.money.MonetaryAmountDeserializer.checkPresent(MonetaryAmountDeserializer.java:73)
        at org.zalando.jackson.datatype.money.MonetaryAmountDeserializer.deserialize(MonetaryAmountDeserializer.java:64)
        at org.zalando.jackson.datatype.money.MonetaryAmountDeserializer.deserialize(MonetaryAmountDeserializer.java:21)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        ... 18 more
```

## Expected Behavior
I expected it to work.

## Actual Behavior
I get the error pasted above.

## Possible Fix
Unlike JSON, CSV does not support nested properties, which I suspect interferes with the idea of how `jackson-dataformat-csv` works by default. But it should still be possible to parse a monetary value; currency could be set on the mapper instead of taking it from the field.

**Comment by whiskeysierra** [comment]
> currency could be set on the mapper instead of taking it from the field.

No, that completely negates the purpose of this library.
The idea is to represent money as a complete, self-contained value.
That includes the amount as well as the currency.
This library clearly targets JSON.
While Jackson nowadays supports other formats, all except JSON are kinda shoehorned into it and I only consider JSON as the canonical data format that Jackson was meant to target.
