### ISSUE TITLE
Known issue with setters on MonetaryAmount

### ISSUE THREAD

**Issue by soberich** [zalando/jackson-datatype-money#82]
Hi, 
There is a known issue but no known workaround.
tried Jackson 2.9.5, 2.9.4, and some else..
```
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "number": javax.money.MonetaryAmountFactory#setNumber(1 params) vs javax.money.MonetaryAmountFactory#setNumber(1 params)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:497)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._renameUsing(POJOPropertiesCollector.java:848)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:336)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
        at deployment.test-1.0.0-SNAPSHOT.war//com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:468)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:560)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:560)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:361)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:560)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:90)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.core.converter.ModelConverters.resolveAsResolvedSchema(ModelConverters.java:112)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:943)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.Reader.parseMethod(Reader.java:748)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.Reader.read(Reader.java:422)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.Reader.read(Reader.java:169)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.Reader.read(Reader.java:196)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.oas.integration.GenericOpenApiContext.read(GenericOpenApiContext.java:347)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.integration.resources.BaseOpenApiResource.getOpenApi(BaseOpenApiResource.java:49)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.integration.resources.OpenApiResource.getOpenApi(OpenApiResource.java:32)
        at deployment.test-1.0.0-SNAPSHOT.war//io.swagger.v3.jaxrs2.integration.resources.OpenApiResource$Proxy$_$$_WeldClientProxy.getOpenApi(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:400)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:364)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:359)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:366)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:311)
        at org.jboss.resteasy.resteasy-jaxrs//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:437)
        ... 64 more
```

It is super annoying as the whole project could've be completely automated but with this all MonetaryAmounts have be treated specially. Please advise.

**Comment by whiskeysierra** [comment]
We're using jackson 2.9.5 successfully in this project. What are you trying to do? Can you share some code? Jackson shouldn't need to know about `javax.money.MonetaryAmountFactory#setNumber`, afaict.

**Comment by soberich** [comment]
Which part of the code do you need?
I simply have POJOs where there are fields of type MonetaryAmount and during deployment of the app, probably during initializing providers like RestEasyJackson2Provider and all other stuff with resteasy-servlet-initializer, and while Swagger does the same trying to generate Api defenitions with it's own same stuff like its own version of resteasy-servlet-initializer and Jackson ObjectMapper which is the essential part, the exception thrown.
Both Swagger (the very last version 2.0.1) and my my app bundled Jackson version is 2.9.5
Let's try to resolve this. What do you need?

**Comment by soberich** [comment]
Ok, I see this is a swagger issue.
Also linked here https://github.com/FasterXML/jackson-databind/issues/1251.
